app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::bind('websites', function($value, $route) {
	return App\Website::whereId($value)->first();
});

Route::bind('categories', function($value, $route) {
	return App\Category::whereId($value)->first();
});

Route::bind('tags', function($value, $route) {
	return App\Tag::whereId($value)->first();
});
Route::bind('synonyms', function($value, $route) {
	return App\Synonym::whereId($value)->first();
});

Route::bind('feeds', function($value, $route) {
	return App\Feed::whereId($value)->first();
});
Route::bind('feeditems', function($value, $route) {
	return App\Feed_item::whereId($value)->first();
});

Route::auth();
Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function()
{

	Route::get('/', 'AdminController@index');
	Route::get('artisan/{command}', 'ArtisanController@handler');
	Route::get('graph/feed_count', 'GraphController@feed_item_count');

	Route::resource('websites', 'WebsiteController');
	Route::get('websites/select/{id}', 'WebsiteController@select');

	Route::resource('categories', 'CategoryController');


	Route::get('/tags/ajax_get_synonym_form', 'TagController@ajax_get_synonym_form');
	Route::get('/tags/ajax_get_tags', 'TagController@ajax_get_tags');
	Route::resource('tags', 'TagController');
	Route::delete('/synonyms/{id}', 'TagSynonymController@destroy');

	Route::resource('feeds', 'FeedController');
	Route::resource('feeditems', 'FeedItemController');
	Route::post('feeditems/search', [
		'as' => 'admin.feeditems.search',
		'uses' => 'FeedItemController@search'
	]);
	Route::get('feeditems/reset_search', [
	  'as' => 'admin.feeditems.reset_search',
		'uses' => 'FeedItemController@reset_search'
	]);

	Route::get('fix_images_feed_items', 'FeedItemCronController@fix_images');
	Route::get('daily_fb_post', 'FacebookController@post_daily_trending_feed_item');
	Route::get('{table}/{id}/{status}',  'StatusController@set_object_state');
});
Route::get('cron/feed/items/{website_id}', 'Backend\FeedItemCronController@run_cron');


Route::get('/admin/sitemap/{site}', 'SitemapController@manuel');

Route::group(['domain' => '{site}.nl', 'middleware' => 'currentsite', 'namespace' => 'Frontend'], function()
{
	Route::get('/', 'HomeController@index');
	Route::get('/search', 'SearchController@search');
	Route::get('/{slug}', 'CategoryController@index');
	Route::get('/item/{id}', 'FeedItemController@index');
	Route::get('/item/{id}/leave', 'FeedItemController@leave');
	Route::get('/item/{id}/{item_name}', 'FeedItemController@index');

});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $guarded = [];

    public function synonyms(){
      return $this->hasMany('App\Synonym');
    }

    public function categories(){
      return $this->belongsToMany('App\Category');
    }
}

app/Http/Controllers/Backend/TagController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Tag;
use App\Synonym;
use Session;
use Input;
use Redirect;
use DB;

class TagController extends BackendController
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $tags = Tag::get();

      return view('tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $tag = new Tag();
        return view('tags.create', compact('tag'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $input = Input::all();

      $synonyms = $input['synonym'];
      unset($input['synonym']);

      $tag = Tag::create( $input );

      foreach($synonyms as $synonym){
        $synonym['tag_id'] = $tag->id;
        Synonym::create($synonym);
      }

      return Redirect::route('admin.tags.index')->with('message', 'Tag created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
          return view('tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
      $input = array_except(Input::all(), '_method');


      $synonyms = $input['synonym'];
      unset($input['synonym']);

      $tag->update($input);


      foreach($synonyms as $id => $synonym_data){
        if(!empty($synonym_data['id'])){
          $synonym = Synonym::where('id', $synonym_data['id'])->first();
          if(!is_null($synonym)){
            $synonym->title = $synonym_data['title'];
            $synonym->save();
          }
        }
        else {
          $synonym = new Synonym();
          $synonym->title = $synonym_data['title'];
          $synonym->tag_id = $tag->id;
          $synonym->save();
        }
      }

      return Redirect::route('admin.tags.index')->with('message', 'Tag updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
      $tag->delete();
      return Redirect::route('admin.tags.index')->with('message', 'Tag deleted.');
    }

    public function ajax_get_synonym_form(){
      return view('tags.partials._synonym');
    }

    public function ajax_get_tags(){
      $tags = DB::table('tags')->where('status', 'A')->select('id', 'title as text')->get();
      return $tags;
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header"><div class="card-title"><div class="title">Tags</div></div></div>
      <div class="card-body">
        {!! Form::model($tag, ['route' => ['admin.tags.store'], 'class' => 'form-horizontal']) !!}
            @include('tags/partials/_form', ['submit_text' => 'Create tag'])
        {!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
			<div class="card-header"><div class="card-title"><div class="title">Tags</div></div></div>
			<div class="card-body">
        {!! Form::model($tag, ['method' => 'PATCH', 'route' => ['admin.tags.update', $tag->id], 'class' => 'form-horizontal']) !!}
            @include('tags/partials/_form', ['submit_text' => 'Update tag'])
        {!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
			<div class="card-header"><div class="card-title"><div class="title">Tags</div></div></div>
			<div class="card-body">
				<div class="btn-group">
					<a href="{!! route('admin.tags.create') !!}" class="btn btn-success">Create tag</a>
				</div>
        <table class="table table-striped">
          <thead>
            <th>Title</th>
            <th>Status</th>
          </thead>
          @foreach( $tags as $tag )
            <tr>
              <td>
                {{ $tag->title }}</a>
              </td>
              <td class="column-actions">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-gear"></i> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li>{!! link_to_route('admin.tags.edit', 'Edit', array($tag->id)) !!}</li>
                    <li>{!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.tags.destroy', $tag->id))) !!}
                           {!! Form::submit('Delete') !!}
                       {!! Form::close() !!}</li>
                  </ul>
                </div>
              </td>
              <td class="column-status">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span>
                    @if ($tag->status == 'A')
                      Active
                    @else
                      Disabled
                    @endif
                    </span>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                      <li><a class="update-object-status" data-table="tags" data-id="{{$tag->id}}" data-status="A">Active</a></li>
                      <li><a class="update-object-status" data-table="tags" data-id="{{$tag->id}}" data-status="D">Disabled</a></li>
                  </ul>
                </div>
              </td>
            </tr>
          @endforeach
        </table>
			</div>
		</div>
	</div>
</div>
@endsection