app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::bind('websites', function($value, $route) {
	return App\Website::whereId($value)->first();
});

Route::bind('categories', function($value, $route) {
	return App\Category::whereId($value)->first();
});

Route::bind('tags', function($value, $route) {
	return App\Tag::whereId($value)->first();
});
Route::bind('synonyms', function($value, $route) {
	return App\Synonym::whereId($value)->first();
});

Route::bind('feeds', function($value, $route) {
	return App\Feed::whereId($value)->first();
});
Route::bind('feeditems', function($value, $route) {
	return App\Feed_item::whereId($value)->first();
});

Route::auth();
Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function()
{

	Route::get('/', 'AdminController@index');
	Route::get('artisan/{command}', 'ArtisanController@handler');
	Route::get('graph/feed_count', 'GraphController@feed_item_count');

	Route::resource('websites', 'WebsiteController');
	Route::get('websites/select/{id}', 'WebsiteController@select');

	Route::resource('categories', 'CategoryController');


	Route::get('/tags/ajax_get_synonym_form', 'TagController@ajax_get_synonym_form');
	Route::get('/tags/ajax_get_tags', 'TagController@ajax_get_tags');
	Route::resource('tags', 'TagController');
	Route::delete('/synonyms/{id}', 'TagSynonymController@destroy');

	Route::resource('feeds', 'FeedController');
	Route::resource('feeditems', 'FeedItemController');
	Route::post('feeditems/search', [
		'as' => 'admin.feeditems.search',
		'uses' => 'FeedItemController@search'
	]);
	Route::get('feeditems/reset_search', [
	  'as' => 'admin.feeditems.reset_search',
		'uses' => 'FeedItemController@reset_search'
	]);

	Route::get('fix_images_feed_items', 'FeedItemCronController@fix_images');
	Route::get('daily_fb_post', 'FacebookController@post_daily_trending_feed_item');
	Route::get('{table}/{id}/{status}',  'StatusController@set_object_state');
});
Route::get('cron/feed/items/{website_id}', 'Backend\FeedItemCronController@run_cron');


Route::get('/admin/sitemap/{site}', 'SitemapController@manuel');

Route::group(['domain' => '{site}.nl', 'middleware' => 'currentsite', 'namespace' => 'Frontend'], function()
{
	Route::get('/', 'HomeController@index');
	Route::get('/search', 'SearchController@search');
	Route::get('/{slug}', 'CategoryController@index');
	Route::get('/item/{id}', 'FeedItemController@index');
	Route::get('/item/{id}/leave', 'FeedItemController@leave');
	Route::get('/item/{id}/{item_name}', 'FeedItemController@index');

});

app/Website.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Website extends Model
{
    protected $guarded = [];

    public function categories(){
      return $this->hasMany('Category');
    }
}

app/Http/Controllers/Backend/WebsiteController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Website;
use Input;
use Redirect;
use Session;

class WebsiteController extends BackendController
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $websites = Website::all();
        return view('websites.index', compact('websites'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $website = new Website();
        return view('websites.create', compact('website'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = Input::all();
        Website::create( $input );

        if(!Session::has('website'))
        {
          $website = Website::where('status', '=', 'A')->first();
          if($website){
            Session::set('website', $website);
          }

        }

        return Redirect::route('admin.websites.index')->with('message', 'Website created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Website $website)
    {
        return view('websites.edit', compact('website'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Website $website)
    {
      //$this->validate($request, $this->rules);

      $input = array_except(Input::all(), '_method');
      $website->update($input);

      return Redirect::route('admin.websites.index', $website->id)->with('message', 'Website updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Website $website)
    {
      $current_website = Session::get('website');
      if(isset($current_website)){
        if($current_website->id == $website->id){
          $new_current_website = Website::where('status', '=', 'A')->where('id', '!=', $website->id)->first();
          Session::set('website', $new_current_website);
        }
      }

      $website->delete();
      return Redirect::route('admin.websites.index')->with('message', 'Website deleted.');
    }


    public function select($id){
      $website = Website::find($id);
      Session::set('website', $website);
      return redirect()->back();
    }
}

resources/views/websites/create.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
			<div class="card-header"><div class="card-title"><div class="title">Websites</div></div></div>
			<div class="card-body">
        {!! Form::model($website, ['route' => ['admin.websites.store'], 'class' => 'form-horizontal']) !!}
            @include('websites/partials/_form', ['submit_text' => 'Create website'])
        {!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/websites/edit.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
    <div class="card-header"><div class="card-title"><div class="title">Websites</div></div></div>
      <div class="card-body">
        {!! Form::model($website, ['method' => 'PATCH', 'route' => ['admin.websites.update', $website->id], 'class' => 'form-horizontal']) !!}
            @include('websites/partials/_form', ['submit_text' => 'Update website'])
        {!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/websites/index.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
  	<div class="card">
			<div class="card-header"><div class="card-title"><div class="title">Websites</div></div></div>
			<div class="card-body">
				<div class="btn-group">
					<a href="{!! route('admin.websites.create') !!}" class="btn btn-success">Create website</a>
				</div>
				<table class="table table-striped">
          <thead>
            <th>Title</th>
            <th></th>
            <th></th>
          </thead>
          @foreach( $websites as $website )
            <tr>
              <td>
                <a href="{{ $website->url }}" target="blank">{{ $website->title }}</a>
              </td>
              <td class="column-actions">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-gear"></i> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li>{!! link_to_route('admin.websites.edit', 'Edit', array($website->id)) !!}</li>
                    <li>{!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.websites.destroy', $website->id))) !!}
                           {!! Form::submit('Delete') !!}
                       {!! Form::close() !!}</li>
                  </ul>
                </div>
              </td>
              <td class="column-status">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span>
                    @if ($website->status == 'A')
                      Active
                    @else
                      Disabled
                    @endif
                    </span>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                      <li><a class="update-object-status" data-table="websites" data-id="{{$website->id}}" data-status="A">Active</a></li>
                      <li><a class="update-object-status" data-table="websites" data-id="{{$website->id}}" data-status="D">Disabled</a></li>
                  </ul>
                </div>
              </td>
            </tr>
          @endforeach
				</table>
			</div>
		</div>
	</div>
</div>
@endsection