app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::bind('websites', function($value, $route) {
	return App\Website::whereId($value)->first();
});

Route::bind('categories', function($value, $route) {
	return App\Category::whereId($value)->first();
});

Route::bind('tags', function($value, $route) {
	return App\Tag::whereId($value)->first();
});
Route::bind('synonyms', function($value, $route) {
	return App\Synonym::whereId($value)->first();
});

Route::bind('feeds', function($value, $route) {
	return App\Feed::whereId($value)->first();
});
Route::bind('feeditems', function($value, $route) {
	return App\Feed_item::whereId($value)->first();
});

Route::auth();
Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function()
{

	Route::get('/', 'AdminController@index');
	Route::get('artisan/{command}', 'ArtisanController@handler');
	Route::get('graph/feed_count', 'GraphController@feed_item_count');

	Route::resource('websites', 'WebsiteController');
	Route::get('websites/select/{id}', 'WebsiteController@select');

	Route::resource('categories', 'CategoryController');


	Route::get('/tags/ajax_get_synonym_form', 'TagController@ajax_get_synonym_form');
	Route::get('/tags/ajax_get_tags', 'TagController@ajax_get_tags');
	Route::resource('tags', 'TagController');
	Route::delete('/synonyms/{id}', 'TagSynonymController@destroy');

	Route::resource('feeds', 'FeedController');
	Route::resource('feeditems', 'FeedItemController');
	Route::post('feeditems/search', [
		'as' => 'admin.feeditems.search',
		'uses' => 'FeedItemController@search'
	]);
	Route::get('feeditems/reset_search', [
	  'as' => 'admin.feeditems.reset_search',
		'uses' => 'FeedItemController@reset_search'
	]);

	Route::get('fix_images_feed_items', 'FeedItemCronController@fix_images');
	Route::get('daily_fb_post', 'FacebookController@post_daily_trending_feed_item');
	Route::get('{table}/{id}/{status}',  'StatusController@set_object_state');
});
Route::get('cron/feed/items/{website_id}', 'Backend\FeedItemCronController@run_cron');


Route::get('/admin/sitemap/{site}', 'SitemapController@manuel');

Route::group(['domain' => '{site}.nl', 'middleware' => 'currentsite', 'namespace' => 'Frontend'], function()
{
	Route::get('/', 'HomeController@index');
	Route::get('/search', 'SearchController@search');
	Route::get('/{slug}', 'CategoryController@index');
	Route::get('/item/{id}', 'FeedItemController@index');
	Route::get('/item/{id}/leave', 'FeedItemController@leave');
	Route::get('/item/{id}/{item_name}', 'FeedItemController@index');

});

app/Feed_item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence;

class Feed_item extends Model
{
    use Eloquence;

    protected $guarded = [];
    protected $searchableColumns = ['title', 'description'];



    protected $dates = ['created_at', 'updated_at', 'pub_date'];

    public function meta_data(){
      return $this->hasMany('App\Feed_item_meta_data');
    }

    public function categories(){
      return $this->belongsToMany('App\Category');
    }

    public function feed(){
      return $this->belongsTo('App\Feed');
    }

    public function feed_item_popularities(){
      return $this->hasMany('App\Feed_item_popularity');
    }
}

app/Http/Controllers/Backend/FeedItemController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Feed_item;
use Session;
use Redirect;
use Input;
use App\Category;

class FeedItemController extends BackendController
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
      if(!Session::has('website'))
      {
        return Redirect::route('admin.websites.index')->with('message', 'No website found!');
      }
      $website = Session::get('website');
      $input = Input::all();

      $feeditems = Feed_item::where('website_id', '=', $website->id);
      $search = '';
      if(!empty($input['search'])){
        $search = $input['search'];
        $feeditems->search($search);
      }
      $feeditems->orderBy('pub_date', 'DESC');
      $feeditems = $feeditems->paginate(12);

      return view('feeditems.index', compact('feeditems', 'search'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Feed_item $feed_item)
    {
      if(!Session::has('website'))
      {
        return Redirect::route('admin.websites.index')->with('message', 'No website found!');
      }
      $website = Session::get('website');
      $categories_from_db = Category::whereWebsiteId($website->id)->get()->toArray();

      $categories = array();
      foreach($categories_from_db as $category){
        $categories[$category['id']] = $category['title'];
      }

      $selected_categories = array();
      foreach($feed_item->categories as $category){
        $selected_categories[$category->id] = $category->title;
      }


      return view('feeditems.edit', compact('feed_item', 'categories', 'selected_categories'));
    }

    public function update(Feed_item $feed_item){
      $input = Input::all();
      $feed_item->categories()->sync($input['selected_categories']);

      return Redirect::route('admin.feeditems.index')->with('message', 'Feeditem updated');
    }
}

app/Http/Controllers/Frontend/FeedItemController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Feed_item;
use App\Feed_item_popularity;
use Session;
use Jaybizzle\CrawlerDetect\CrawlerDetect;
use Redirect;
use SEOMeta;
use OpenGraph;
use URL;

class FeedItemController extends FrontendController
{
    public function index(Request $request, $slug, $id, $item_name = ''){
      $website = Session::get('frontend_website');

      $item = Feed_item::where('website_id', $website->id)->where('id', $id)->first();
      if($item == null){
        return view('404');
      }
      Session::set('breadcrumb_category', $item->categories->first());

      $this->feed_item_popularity_add($request, $id);

      SEOMeta::setTitle($item->title);
      SEOMeta::setCanonical($request->url());
      OpenGraph::setTitle($item->title);
      OpenGraph::addImage(URL::to('/') . '/' . $item->image);

      return view('frontend.item.view', compact('item'));
    }

    public function feed_item_popularity_add(Request $request, $id, $value = 10){

      $CrawlerDetect = new CrawlerDetect;
      if($CrawlerDetect->isCrawler()){
        return false;
      }

      $pop_record = feed_item_popularity::where('client_ip', $request->ip())
      ->where('feed_item_id', $id)
      ->where('date', date('Y-m-d'))
      ->where('popularity', $value)
      ->first();
      if ($pop_record !== null) {
        return true;
      }
      $data = array();
      $data['feed_item_id'] = $id;
      $data['popularity'] = $value;
      $data['client_ip'] = $request->ip();
      $data['date'] = date('Y-m-d');

      feed_item_popularity::create($data);
      return true;
    }

    public function leave(Request $request, $slug, $id){
      $website = Session::get('frontend_website');
      $item = Feed_item::where('website_id', $website->id)->where('id', $id)->first();
      if($item == null){
        return view('404');
      }
      $this->feed_item_popularity_add($request, $id, 50);

      return Redirect::away($item->link . '/?ref=dragle');
    }
}

resources/views/feeditems/edit.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
    <div class="card-header"><div class="card-title"><div class="title">Feed items</div></div></div>
      <div class="card-body">
        {!! Form::model($feed_item, ['method' => 'PATCH', 'route' => ['admin.feeditems.update', $feed_item->id], 'class' => 'form-horizontal']) !!}
            @include('feeditems/partials/_form', ['submit_text' => 'Update feed item'])
        {!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/feeditems/index.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="title">Feed items</div>
        </div>
      </div>
      <div class="card-body">
        {!! Form::open(['method'=> 'GET', 'route' => ['admin.feeditems.index'], 'class' => 'form-horizontal']) !!}
          <div class="input-group">
            <input placeholder="Search..." type="text" class="form-control" name="search" value="{{$search}}"/>
            <div class="input-group-btn">
              <button class="btn btn-secondary" type="submit"><i class="fa fa-search"></i></button>
            </div>
          </div>
        {!! Form::close() !!}
        <table class="table table-striped">
          <thead>
            <th>Title</th>
            <th></th>
            <th></th>
          </thead>
          @foreach( $feeditems as $feeditem )
            <tr>
              <td>
                <a href="{{ $feeditem->url }}" target="blank">{{ $feeditem->title }}</a>
                <span class="sub-title company">{{ $feeditem->feed->title}}</span>
              </td>
              <td class="column-actions">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-gear"></i> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li>{!! link_to_route('admin.feeditems.edit', 'Edit', array($feeditem->id)) !!}</li>
                    <!--<li>{!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.feeditems.destroy', $feeditem->id))) !!}
                           {!! Form::submit('Delete') !!}
                       {!! Form::close() !!}</li>-->
                  </ul>
                </div>
              </td>
              <td class="column-status">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span>
                    @if ($feeditem->status == 'A')
                      Active
                    @else
                      Disabled
                    @endif
                    </span>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                      <li><a class="update-object-status" data-table="feed_items" data-id="{{$feeditem->id}}" data-status="A">Active</a></li>
                      <li><a class="update-object-status" data-table="feed_items" data-id="{{$feeditem->id}}" data-status="D">Disabled</a></li>
                  </ul>
                </div>
              </td>
            </tr>
          @endforeach
        </table>
        {{ $feeditems->appends(Request::only('search'))->render() }}
			</div>
		</div>
	</div>
</div>
@endsection