app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::bind('websites', function($value, $route) {
	return App\Website::whereId($value)->first();
});

Route::bind('categories', function($value, $route) {
	return App\Category::whereId($value)->first();
});

Route::bind('tags', function($value, $route) {
	return App\Tag::whereId($value)->first();
});
Route::bind('synonyms', function($value, $route) {
	return App\Synonym::whereId($value)->first();
});

Route::bind('feeds', function($value, $route) {
	return App\Feed::whereId($value)->first();
});
Route::bind('feeditems', function($value, $route) {
	return App\Feed_item::whereId($value)->first();
});

Route::auth();
Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function()
{

	Route::get('/', 'AdminController@index');
	Route::get('artisan/{command}', 'ArtisanController@handler');
	Route::get('graph/feed_count', 'GraphController@feed_item_count');

	Route::resource('websites', 'WebsiteController');
	Route::get('websites/select/{id}', 'WebsiteController@select');

	Route::resource('categories', 'CategoryController');


	Route::get('/tags/ajax_get_synonym_form', 'TagController@ajax_get_synonym_form');
	Route::get('/tags/ajax_get_tags', 'TagController@ajax_get_tags');
	Route::resource('tags', 'TagController');
	Route::delete('/synonyms/{id}', 'TagSynonymController@destroy');

	Route::resource('feeds', 'FeedController');
	Route::resource('feeditems', 'FeedItemController');
	Route::post('feeditems/search', [
		'as' => 'admin.feeditems.search',
		'uses' => 'FeedItemController@search'
	]);
	Route::get('feeditems/reset_search', [
	  'as' => 'admin.feeditems.reset_search',
		'uses' => 'FeedItemController@reset_search'
	]);

	Route::get('fix_images_feed_items', 'FeedItemCronController@fix_images');
	Route::get('daily_fb_post', 'FacebookController@post_daily_trending_feed_item');
	Route::get('{table}/{id}/{status}',  'StatusController@set_object_state');
});
Route::get('cron/feed/items/{website_id}', 'Backend\FeedItemCronController@run_cron');


Route::get('/admin/sitemap/{site}', 'SitemapController@manuel');

Route::group(['domain' => '{site}.nl', 'middleware' => 'currentsite', 'namespace' => 'Frontend'], function()
{
	Route::get('/', 'HomeController@index');
	Route::get('/search', 'SearchController@search');
	Route::get('/{slug}', 'CategoryController@index');
	Route::get('/item/{id}', 'FeedItemController@index');
	Route::get('/item/{id}/leave', 'FeedItemController@leave');
	Route::get('/item/{id}/{item_name}', 'FeedItemController@index');

});

app/Feed.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feed extends Model
{
  protected $guarded = [];

  public function feed_items(){
    return $this->hasMany('App\Feed_item');
  }
}

app/Http/Controllers/Backend/FeedController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Feed;
use App\Website;
use Session;
use Redirect;
use Input;

class FeedController extends BackendController
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      if(!Session::has('website'))
      {
        return Redirect::route('websites.index')->with('message', 'No website found!');
      }
      $website = Session::get('website');
      $feeds = Feed::where('website_id', '=', $website->id)->get();

      return view('feeds.index', compact('feeds'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $feed = new Feed();
      return view('feeds.create', compact('feed'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $input = Input::all();

      if(!Session::has('website'))
      {
        return Redirect::route('admin.websites.index')->with('message', 'No website found!');
      }
      $website = Session::get('website');
      $input['website_id'] = $website->id;

      $feed = Feed::create( $input );

      return Redirect::route('admin.feeds.index')->with('message', 'Feed created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Feed $feed)
    {
      return view('feeds.edit', compact('feed'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Feed $feed)
    {
      $input = array_except(Input::all(), '_method');

      $feed->update($input);

      return Redirect::route('admin.feeds.index')->with('message', 'Feed updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Feed $feed)
    {
      $feed->delete();
      return Redirect::route('admin.feeds.index')->with('message', 'Feed deleted.');
    }
}

resources/views/feeds/create.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
			<div class="card-header"><div class="card-title"><div class="title">Feeds</div></div></div>
				<div class="card-body">
          {!! Form::model($feed, ['route' => ['admin.feeds.store'], 'class' => 'form-horizontal']) !!}
              @include('feeds/partials/_form', ['submit_text' => 'Create feed'])
          {!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/feeds/edit.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
			<div class="card-header"><div class="card-title"><div class="title">Feeds</div></div></div>
			<div class="card-body">
        {!! Form::model($feed, ['method' => 'PATCH', 'route' => ['admin.feeds.update', $feed->id], 'class' => 'form-horizontal']) !!}
            @include('feeds/partials/_form', ['submit_text' => 'Update feed'])
        {!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/feeds/index.blade.php
@extends('layouts.app')

<!-- Main Content -->
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
			<div class="card-header"><div class="card-title"><div class="title">Feeds</div></div></div>
			<div class="card-body">
				<div class="btn-group">
					<a href="{!! route('admin.feeds.create') !!}" class="btn btn-success">Create feed</a>
				</div>
				<table class="table table-striped">
          <thead>
            <th>Title</th>
            <th></th>
            <th></th>
          </thead>
          @foreach( $feeds as $feed )
            <tr>
              <td>
                <a href="{{ $feed->url }}" target="blank">{{ $feed->title }}</a>
              </td>
              <td>
                <span class="badge">{{$feed->feed_items->count() }}</span>
              </td>
              <td class="column-actions">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-gear"></i> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li>{!! link_to_route('admin.feeds.edit', 'Edit', array($feed->id)) !!}</li>
                    <li>{!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.feeds.destroy', $feed->id))) !!}
                           {!! Form::submit('Delete') !!}
                       {!! Form::close() !!}</li>
                  </ul>
                </div>
              </td>
              <td class="column-status">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span>
                    @if ($feed->status == 'A')
                      Active
                    @else
                      Disabled
                    @endif
                    </span>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                      <li><a class="update-object-status" data-table="feeds" data-id="{{$feed->id}}" data-status="A">Active</a></li>
                      <li><a class="update-object-status" data-table="feeds" data-id="{{$feed->id}}" data-status="D">Disabled</a></li>
                  </ul>
                </div>
              </td>
            </tr>
          @endforeach
				</table>
			</div>
		</div>
	</div>
</div>
@endsection